<a href="https://colab.research.google.com/github/mialdrid/Python/blob/master/MDAldridge_IndividualAssignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Michael Aldridge
Individual Assignment 2




Part 1

In [1]:
# Import package
import nltk
nltk.download('punkt') # tokenizer
nltk.download('wordnet') # lemmatizer
nltk.download('stopwords') # used to handle words like a, an, the
nltk.download('averaged_perceptron_tagger') # Part of Speech
import pandas as pd
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [2]:
# Store GitHub link to Excel sheet as a variable
GitHubUrl= 'https://raw.githubusercontent.com/mialdrid/Python/master/IA2.csv'
# Read csv file into dataframe 
df = pd.read_csv(GitHubUrl,header=None)
df.columns = ['index', 'comment']
#head df to view results
df.head()

index                                            comment
0      1  This is the place to go after this branch to t...
1      2  The direct delivery from Star Theater in Chian...
2      3  It is very delicious food. Good taste Unspoilt...
3      4  This house is the second time. I used to be a ...
4      5  Featured is majestic. Located on the road 107 ...

In [3]:
#Tokenize each comment/row
for row in df.comment:
  comments = nltk.word_tokenize(row)

print(comments)

['Some', 'of', 'Liu', 'Zhenyun', '’', 's', 'works', 'have', 'been', 'read', 'intermittently', '.', 'The', 'small', 'forest', 'in', 'the', '“', 'Unit', '”', 'and', '“', 'Chicken', 'of', 'the', 'Land', '”', 'grew', 'up', 'under', 'the', 'reform', 'and', 'opening', 'up', 'and', 'the', 'market', 'economy', '.', 'Many', 'historical', 'figures', 'in', 'the', '“', 'Hometown', '”', 'series', 'encircle', 'the', 'historical', 'reality', ',', 'nothing', 'more', 'than', 'Liu', 'Zhenyun', '’', 's', 'black', 'humor', '.', 'The', 'language', 'reveals', 'his', 'embarrassment', 'as', 'a', 'writer', '.', 'The', 'characters', 'are', 'not', 'important', '.', 'What', 'is', 'important', 'is', 'to', 'dispel', 'the', 'grand', 'narrative', 'in', 'the', 'historical', 'context', ',', 'to', 'defeat', 'the', 'tall', 'and', 'complete', ',', 'and', 'to', 'return', 'a', 'real', 'name', 'to', 'the', 'world', '.', 'In', 'Liu', 'Zhenyun', '&', '#', '39', ';', 's', 'works', ',', 'you', 'can', 'almost', 'see', 'too', 'man

In [4]:
#Lemmatize each word in comments
lemmatizer = nltk.stem.WordNetLemmatizer()
lemmatized = [lemmatizer.lemmatize(token) for token in comments if token.isalpha()]
print (lemmatized)

['Some', 'of', 'Liu', 'Zhenyun', 's', 'work', 'have', 'been', 'read', 'intermittently', 'The', 'small', 'forest', 'in', 'the', 'Unit', 'and', 'Chicken', 'of', 'the', 'Land', 'grew', 'up', 'under', 'the', 'reform', 'and', 'opening', 'up', 'and', 'the', 'market', 'economy', 'Many', 'historical', 'figure', 'in', 'the', 'Hometown', 'series', 'encircle', 'the', 'historical', 'reality', 'nothing', 'more', 'than', 'Liu', 'Zhenyun', 's', 'black', 'humor', 'The', 'language', 'reveals', 'his', 'embarrassment', 'a', 'a', 'writer', 'The', 'character', 'are', 'not', 'important', 'What', 'is', 'important', 'is', 'to', 'dispel', 'the', 'grand', 'narrative', 'in', 'the', 'historical', 'context', 'to', 'defeat', 'the', 'tall', 'and', 'complete', 'and', 'to', 'return', 'a', 'real', 'name', 'to', 'the', 'world', 'In', 'Liu', 'Zhenyun', 's', 'work', 'you', 'can', 'almost', 'see', 'too', 'many', 'postmodernist', 'technique', 'rather', 'than', 'the', 'pure', 'modernity', 'of', 'the', 'sorrowful', 'magical',

In [5]:
#Remove punctuation and stop words
stopwords_removed = [token for token in lemmatized if not token in stopwords.words('english')]
print (stopwords_removed)

['Some', 'Liu', 'Zhenyun', 'work', 'read', 'intermittently', 'The', 'small', 'forest', 'Unit', 'Chicken', 'Land', 'grew', 'reform', 'opening', 'market', 'economy', 'Many', 'historical', 'figure', 'Hometown', 'series', 'encircle', 'historical', 'reality', 'nothing', 'Liu', 'Zhenyun', 'black', 'humor', 'The', 'language', 'reveals', 'embarrassment', 'writer', 'The', 'character', 'important', 'What', 'important', 'dispel', 'grand', 'narrative', 'historical', 'context', 'defeat', 'tall', 'complete', 'return', 'real', 'name', 'world', 'In', 'Liu', 'Zhenyun', 'work', 'almost', 'see', 'many', 'postmodernist', 'technique', 'rather', 'pure', 'modernity', 'sorrowful', 'magical', 'realism', 'quot', 'hometown', 'circulate', 'quot', 'six', 'finger', 'excess', 'finger', 'set', 'bridge', 'let', 'Hundreds', 'thousand', 'immigrant', 'Yanjin', 'people', 'successfully', 'crossed', 'Yellow', 'River', 'In', 'new', 'historicalism', 'quot', 'Hometown', 'Yellow', 'Flower', 'quot', 'village', 'committee', 'cadr

In [6]:
#Create TF-IDF Vectors
vectorizer = TfidfVectorizer(ngram_range=(1,2), min_df=3)
vectorizer.fit(stopwords_removed)

vector = vectorizer.transform(stopwords_removed)


print(vector.toarray())
print('\n')
print(vectorizer.vocabulary_)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


{'liu': 13, 'zhenyun': 29, 'the': 22, 'small': 21, 'forest': 3, 'unit': 24, 'chicken': 1, 'historical': 5, 'hometown': 7, 'series': 20, 'nothing': 15, 'language': 10, 'writer': 26, 'narrative': 14, 'real': 19, 'in': 8, 'quot': 18, 'thousand': 23, 'people': 16, 'yellow': 28, 'like': 12, 'history': 6, 'ha': 4, 'it': 9, 'everyone': 2, 'life': 11, 'change': 0, 'power': 17, 'year': 27, 'wa': 25}


In [7]:
#POS
# Tag each word from output one with Part of Speech

comments

POS = []
for comment in comments:
    tokens = nltk.word_tokenize(comment) # tokenize the words
    POS_tokens = nltk.pos_tag(tokens) # pos tag the tokens
    POS_token_temp = []
    for i in POS_tokens:
        POS_token_temp.append(i[0] + i[1]) # create tuples for the tokens/pos tags
    POS.append(" ".join(POS_token_temp))

vectorizer2 = TfidfVectorizer()
vectorizer2.fit(POS)
print(vectorizer2.vocabulary_)

print('\n')

POS_2 = vectorizer2.transform(POS)
print(POS_2.toarray())

{'somedt': 280, 'ofin': 208, 'liunn': 167, 'zhenyunnn': 356, 'nn': 199, 'snn': 277, 'worksnns': 344, 'havevb': 118, 'beenvbn': 25, 'readnn': 239, 'intermittentlyrb': 145, 'thedt': 303, 'smalljj': 275, 'forestnn': 95, 'inin': 143, 'unitnn': 321, 'andcc': 14, 'chickennn': 45, 'landnn': 154, 'grewvbd': 111, 'uprb': 324, 'underin': 319, 'reformnn': 245, 'openingnn': 215, 'marketnn': 177, 'economynn': 69, 'manyjj': 176, 'historicaljj': 129, 'figuresnns': 86, 'hometownnnp': 132, 'seriesnn': 268, 'encirclenn': 72, 'realitynn': 243, 'nothingnn': 201, 'morerbr': 189, 'thanin': 301, 'blackjj': 30, 'humornn': 136, 'languagenn': 155, 'revealsnns': 254, 'hisprp': 127, 'embarrassmentnn': 70, 'asin': 17, 'adt': 6, 'writernn': 347, 'charactersnns': 44, 'arevbp': 16, 'notrb': 202, 'importantjj': 141, 'whatwp': 338, 'isvbz': 149, 'toto': 313, 'dispelnn': 64, 'grandjj': 109, 'narrativejj': 193, 'contextnn': 52, 'defeatnn': 58, 'tallnn': 295, 'completejj': 51, 'returnnn': 253, 'realjj': 244, 'namenn': 192

Part 2

In [0]:
# Import
from google.colab import files
import os
import numpy as np
from PIL import Image
from pylab import *

In [9]:
#loop through and add each image to a list
# for loop to grab all of the files from the current working directory

#create a list to store png images in
PNGImages = []
for img_path in os.listdir():
  # PNG files
  if img_path.endswith(".PNG"):
      #reading images
      img = Image.open(img_path)
      #convert to grayscale
      img = img.convert('L')
      #resize 100 x 100 pixels
      img = np.resize(im,(100,100,3))
      #flatten to a 1D array
      img = img.flatten()
      #append each image to the list
      PNGImages.append(img)


# plotting the image arrays in a histogram with 256 bins
plt.hist(PNGImages,bins=255,stacked=True)

NameError: ignored

In [0]:
#Create a new list
PNGImages_2 =[]
# for loop to grab all of the files from the current working directory
for img_path in os.listdir():
  # grabbing all PNG files
  if img_path.endswith(".PNG"):
      #reading in the images
      img = Image.open(img_path)
      #converting them to grayscale
      img = img.convert('L')
      #resizing them to 100 x 100 pixels
      img = np.resize(im,(100,100,3))
      #flattening the 2D array to a 1D array
      img = img.flatten()
      img, bins = histogram(img, 256, density=True)
      img = img.cumsum()
      img = 255 * img / img[-1] # Normalization to ensure that we are in [0,255]
      #appending the image arrays to the list I initiated earlier
      PNGImages_2.append(img)

# plotting the image arrays in a histogram with 256 bins
plt.hist(PNGImages_2, bins=255, stacked=True)